# Generated by Django 3.1.6 on 2021-02-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
