# Generated by Django 3.1.6 on 2021-02-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('user_name', models.CharField(max_length=100)),
                ('article_id', models.IntegerField()),
            ],
            options={
                'ordering': ['article_id'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
